version: "3"

tasks:
  run:
    cmds:
      - |
        curl -XPOST "http://localhost:9005/2015-03-31/functions/function/invocations" -d '{
          "Records": [
            {
              "message": "message-id",
              "eventSource": "event-source",
              "body": ""
            }
          ]
        }'
