services:
  fetcher:
    container_name: rss-fetcher
    environment:
      - AWS_REGION=ap-northeast-1
      - AWS_ACCESS_KEY_ID=oot
      - AWS_SECRET_ACCESS_KEY=secret
      - AWS_LAMBDA_FUNCTION_TIMEOUT=300
    build:
      context: ../go
      dockerfile: ../go/lambda/rss-fetcher/Dockerfile
      target: dev
    volumes:
      - ../go:/app
    ports:
      - "9003:8080"
    depends_on:
      - dynamodb
    networks:
      - apps