services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data -port 8000"
    ports:
      - "8000:8000"
    working_dir: /home/dynamodblocal
    volumes:
      - "./dynamodb:/home/dynamodblocal/data"
    networks:
      - apps
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:8000 || exit 1"]
      interval: 10s
      timeout: 5s

  dynamodb-admin:
    image: "aaronshaf/dynamodb-admin:latest"
    container_name: dynamodb-admin
    environment:
      - AWS_REGION=ap-northeast-1
      - DYNAMO_ENDPOINT=http://dynamodb:8000
    ports:
      - "8001:8001"
    networks:
      - apps
    depends_on:
      - dynamodb

volumes:
  dynamodb-data:

networks:
  apps:
    driver: bridge